require 'coveralls'
Coveralls.wear!

require 'rspec'
require 'rspec/mocks'
require 'tempfile'
# require 'simplecov'
# require 'simplecov-rcov'
require 'byebug'
require "persistent-cache"
require "persistent-cache/storage_sqlite"
require "persistent-cache/storage_directory"
require "persistent-cache/storage_ram"

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

$:.unshift(File.join(File.dirname(__FILE__), '..', 'persistent-cache'))

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  # config.expect_with(:rspec) { |c| c.syntax = :should }

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

# SimpleCov.formatter = SimpleCov::Formatter::RcovFormatter
# SimpleCov.start do
#   add_filter "/spec/"
# end

def get_database_name
  path = Tempfile.new("persistent-cache-spec-testdb").path
  FileUtils.rm_f(path)
  path
end

